apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: node-test
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/test-node:5db4ac212c43876cddadef58e3bdddd4109f4b62@sha256:a630e9268c548c940799ccad8b505fa4fe08b09176d9846edf9ea03c3432430a
          name: container-image
